### PR TITLE
Resolved unsafe random source usage

### LINKED ISSUE #119: [1.19.2] RandomSource crash caused by Savage and Ravage
Crashlog from the user: https://paste.ee/p/tcl0e

The problematic line: https://github.com/team-abnormals/savage-and-ravage/blob/d07f8f3e319597eb9f7855d3cf83fb7ac3456bd3/src/main/java/com/teamabnormals/savage_and_ravage/core/mixin/PillagerMixin.java#L29

a user came into Yung’s discord asking for help with solving a RandomSource crash. I took a look and sure enough, this code in Savage and Ravage is not threadsafe and using the wrong RandomSource. 

The technical reason behind this is that Minecraft’s world generation is multithreaded but RandomSource is not threadsafe. So if during worldgen, someone grabs the ServerLevel instead of WorldGenRegion and uses the random in ServerLevel, then they risk a crash if they use that random at the exact same time as the server thread using the random. This causes the two threads to try and ask the RandomSource for a value at the same time which is illegal and causes a crash.

Here in Savage and Ravage, this mixin into finalizeSpawn runs during worldgen when the Pillager finishes spawning from structures or features or whatever. But this mixin is using the ServerLevel’s random that is passed into the entity’s constructor when entities are first created. Never use this level’s random. Instead, all living entities have their own builtin-field that initializes a RandomSource just for that entity. Use this RandomSource always when working with the entity anywhere (but especially within the entity’s constructor or initialization like where this mixin is)

Switch to this RandomSource and that should greatly help reduce people crashing at completely random times in the overworld and were unable to track down the mod.

Be sure to check all your other mixins and code as well to make sure they all have the correct randomsource usage too. I had a similar crash as well until I refactored my mod to use the entity’s randomsource whenever I had an entity passed in a method’s constructor (like block’s entityInside method) or is within an entity’s class.

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Fixes https://github.com/team-abnormals/savage-and-ravage/issues/119

These are the randomsources that are not safe for threaded code that I can find. Remember, if given a living entity or are inside an entity's class, always use the entity's randomsource so you don't crash vanilla's usage of the level's randomsource that's running on the server thread.

### CODE REVIEW

File: src/main/java/com/teamabnormals/savage_and_ravage/core/other/SREvents.java [hunk 1]
```diff
@@ -142,14 +142,14 @@ public static void onRightClickEntity(PlayerInteractEvent.EntityInteract event)
 			Player player = event.getEntity();
 			CompoundTag persistentData = target.getPersistentData();
 			if (!persistentData.getBoolean(POISON_TAG)) {
-				if (target.level.random.nextDouble() < SRConfig.COMMON.poisonPotatoChance.get()) {
```
Comment (SmellyModder) [inline src/main/java/com/teamabnormals/savage_and_ravage/core/other/SREvents.java]: Shouldn't this be using the `RandomSource` instance of the `target` local variable?

File: src/main/java/com/teamabnormals/savage_and_ravage/core/other/SREvents.java [hunk 2]
```diff
@@ -142,14 +142,14 @@ public static void onRightClickEntity(PlayerInteractEvent.EntityInteract event)
...
+				if (target.level.getRandom().nextDouble() < SRConfig.COMMON.poisonPotatoChance.get()) {
 					target.playSound(SoundEvents.GENERIC_EAT, 0.5f, 0.25f);
 					persistentData.putBoolean(POISON_TAG, true);
 					if (SRConfig.COMMON.poisonPotatoEffect.get()) {
 						((LivingEntity) target).addEffect(new MobEffectInstance(MobEffects.POISON, 200));
 					}
 				} else {
-					target.playSound(SoundEvents.GENERIC_EAT, 0.5f, 0.5f + target.level.random.nextFloat() / 2);
```
Comment (SmellyModder) [inline src/main/java/com/teamabnormals/savage_and_ravage/core/other/SREvents.java]: Shouldn't this be using the `RandomSource` instance of the `target` local variable?

**Review by SmellyModder — CHANGES_REQUESTED** [review]

File: src/main/java/com/teamabnormals/savage_and_ravage/core/other/SREvents.java (hunk 1 above)
Comment (TelepathicGrunt) [reply src/main/java/com/teamabnormals/savage_and_ravage/core/other/SREvents.java]: Technically no as the player interact event runs always on server thread so there's no worry of multithreaded issues. This is a case where server level random is safe. Basically if the code you're in has a chance of running off thread, do not use the level's random. Most people forget the entity constructor and finalizeSpawn method in entities can be ran during worldgen which is offthread and is why those have to use the entity's randomsource and not the level's

Comment (SmellyModder) [reply src/main/java/com/teamabnormals/savage_and_ravage/core/other/SREvents.java]: Ok, I was only checking because I assumed you were only changing stuff necessary/relevant to the fix.
Don't include your changes to the `SREvents` class, then.

**Review by SmellyModder — APPROVED** [review]

**Comment by SmellyModder** [comment]
Thanks for the fix!
